language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t jlucar/react-test ./client

script:
  - docker run -e CI=true jlucar/react-test npm run test

after_success:
  - docker build -t jlucar/multi-client ./client
  - docker build -t jlucar/multi-nginx ./nginx
  - docker build -t jlucar/multi-server ./server
  - docker build -t jlucar/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push jlucar/multi-client
  - docker push jlucar/multi-nginx
  - docker push jlucar/multi-server
  - docker push jlucar/multi-worker